# Generated by Django 5.2.4 on 2026-09-05 14:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_clinicbranch_alter_clinic_options_clinic_address_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, default='', max_length=200)),
                ('description_en', models.TextField(blank=True, default='')),
                ('description_ar', models.TextField(blank=True, default='')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'db_table': 'offers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'is_active', 'starts_at', 'ends_at'], name='offers_clinic__7b8541_idx')],
            },
        ),
    ]
