# Generated by Django 5.2.4 on 2026-09-10 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_clinic_google_maps_url_clinic_google_place_id_and_more'),
        ('media', '0002_mediaasset'),
        ('offers', '0002_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='offer',
            name='media_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='media.mediaasset'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='ends_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='starts_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title_ar',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title_en',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status', 'is_active'], name='offers_status_8f8277_idx'),
        ),
    ]
