# Generated by Django 5.2.4 on 2026-09-06 11:28

import apps.referrals.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_clinicbranch_alter_clinic_options_clinic_address_ar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralDiscountCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=apps.referrals.models.generate_discount_code, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('redeemed', 'Redeemed'), ('expired', 'Expired')], default='active', max_length=20)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=apps.referrals.models.default_expiration)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to=settings.AUTH_USER_MODEL)),
                ('redeemed_clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_codes', to='clinics.clinic')),
            ],
            options={
                'db_table': 'referral_discount_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitee_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referral_invites',
                'ordering': ['-created_at'],
                'unique_together': {('referrer', 'invitee_phone')},
            },
        ),
        migrations.CreateModel(
            name='ReferralPointsLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('milestone_20', 'Milestone 20'), ('milestone_35', 'Milestone 35'), ('milestone_50', 'Milestone 50'), ('collect_code', 'Collect Code'), ('admin_adjustment', 'Admin Adjustment')], max_length=30)),
                ('points', models.IntegerField()),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_ledger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referral_points_ledger',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'created_at'], name='referral_po_patient_0d67a2_idx')],
            },
        ),
    ]
