# Generated by Django 5.2.4 on 2026-09-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referraldiscountcode',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
