# Generated by Django 5.2.4 on 2026-09-13 15:54

from django.db import migrations, models


def migrate_status_forward(apps, schema_editor):
    ReferralDiscountCode = apps.get_model('referrals', 'ReferralDiscountCode')
    ReferralDiscountCode.objects.filter(status='active').update(status='available')
    ReferralDiscountCode.objects.filter(status='redeemed').update(status='used')

def migrate_status_backward(apps, schema_editor):
    ReferralDiscountCode = apps.get_model('referrals', 'ReferralDiscountCode')
    ReferralDiscountCode.objects.filter(status='available').update(status='active')
    ReferralDiscountCode.objects.filter(status='used').update(status='redeemed')

class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_referraldiscountcode_discount_percent'),
    ]

    operations = [
        migrations.RunPython(migrate_status_forward, migrate_status_backward),
        migrations.AlterField(
            model_name='referraldiscountcode',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('used', 'Used'), ('expired', 'Expired')], default='available', max_length=20),
        ),
    ]
