# Generated by Django 5.2.4 on 2026-09-05 11:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('clinic_staff', 'Clinic Staff'), ('clinic_admin', 'Clinic Admin'), ('super_admin', 'Super Admin')], db_index=True, default='patient', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Set to True after successful OTP verification.')),
                ('is_staff', models.BooleanField(default=False, help_text='Allows access to Django admin interface.')),
                ('device_platform', models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=10, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ClinicUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_in_clinic', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to suspend access without deleting the record.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_users', to='clinics.clinic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clinic User',
                'verbose_name_plural': 'Clinic Users',
                'db_table': 'clinic_users',
            },
        ),
        migrations.CreateModel(
            name='OtpRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('password_reset', 'Password Reset')], max_length=30)),
                ('code_hash', models.CharField(max_length=255)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OTP Record',
                'verbose_name_plural': 'OTP Records',
                'db_table': 'otp_records',
                'indexes': [models.Index(fields=['phone', 'purpose', 'is_used'], name='otp_records_phone_7746ac_idx'), models.Index(fields=['expires_at'], name='otp_records_expires_b98a7e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referral_code', models.CharField(max_length=30, unique=True)),
                ('current_points', models.PositiveIntegerField(default=0)),
                ('total_successful_invites', models.PositiveIntegerField(default=0)),
                ('milestone_20_awarded', models.BooleanField(default=False)),
                ('milestone_35_awarded', models.BooleanField(default=False)),
                ('milestone_50_awarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Profile',
                'verbose_name_plural': 'Patient Profiles',
                'db_table': 'patient_profiles',
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField()),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Token',
                'verbose_name_plural': 'Push Tokens',
                'db_table': 'push_tokens',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email',), name='unique_email_when_not_null'),
        ),
        migrations.AddIndex(
            model_name='clinicuser',
            index=models.Index(fields=['clinic', 'is_active'], name='clinic_user_clinic__c2a2b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicuser',
            unique_together={('user', 'clinic')},
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['referral_code'], name='patient_pro_referra_163396_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['current_points'], name='patient_pro_current_38a746_idx'),
        ),
        migrations.AddIndex(
            model_name='pushtoken',
            index=models.Index(fields=['user', 'is_active'], name='push_tokens_user_id_3067f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pushtoken',
            unique_together={('user', 'token')},
        ),
    ]
