# Generated by Django 5.2.4 on 2026-09-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='referred_by_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
