# Generated by Django 5.2.4 on 2026-09-05 14:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_clinicbranch_alter_clinic_options_clinic_address_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, default='', max_length=200)),
                ('title_en', models.CharField(blank=True, default='', max_length=100)),
                ('title_ar', models.CharField(blank=True, default='', max_length=100)),
                ('bio_en', models.TextField(blank=True, default='')),
                ('bio_ar', models.TextField(blank=True, default='')),
                ('speciality_en', models.CharField(blank=True, default='', max_length=200)),
                ('speciality_ar', models.CharField(blank=True, default='', max_length=200)),
                ('license_number', models.CharField(blank=True, default='', max_length=100)),
                ('license_authority', models.CharField(blank=True, default='', max_length=200)),
                ('avatar', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Review')], db_index=True, default='active', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioners', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Practitioner',
                'verbose_name_plural': 'Practitioners',
                'db_table': 'practitioners',
                'ordering': ['display_order', 'name_en'],
                'indexes': [models.Index(fields=['clinic', 'status', 'deleted_at'], name='practitione_clinic__875425_idx')],
            },
        ),
    ]
