# Generated by Django 5.2.4 on 2026-09-10 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_clinic_google_maps_url_clinic_google_place_id_and_more'),
        ('media', '0002_mediaasset'),
        ('practitioners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='media_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioners', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('licensed_professional', 'Licensed Professional')], db_index=True, default='doctor', max_length=30),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='name_ar',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='name_en',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['type', 'status'], name='practitione_type_496522_idx'),
        ),
    ]
