# Generated by Django 5.2.4 on 2026-09-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinicbranch_alter_clinic_options_clinic_address_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='google_maps_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clinic',
            name='google_place_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='clinicbranch',
            name='google_maps_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clinicbranch',
            name='google_place_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
