# Generated by Django 5.2.4 on 2026-09-10 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('treatments', '0002_practitionertreatment_treatment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='treatments.treatment'),
        ),
    ]
