# Generated by Django 5.2.4 on 2026-09-10 00:25

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_clinic_google_maps_url_clinic_google_place_id_and_more'),
        ('practitioners', '0002_practitioner_media_asset_practitioner_type_and_more'),
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PractitionerTreatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_treatments', to='practitioners.practitioner')),
            ],
            options={
                'verbose_name': 'Practitioner Treatment',
                'verbose_name_plural': 'Practitioner Treatments',
                'db_table': 'practitioner_treatments',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(db_index=True, max_length=200)),
                ('name_ar', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('description_en', models.TextField(blank=True, default='')),
                ('description_ar', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], db_index=True, default='active', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='treatments.category')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='clinics.clinic')),
                ('practitioners', models.ManyToManyField(blank=True, related_name='treatments', through='treatments.PractitionerTreatment', to='practitioners.practitioner')),
            ],
            options={
                'verbose_name': 'Treatment',
                'verbose_name_plural': 'Treatments',
                'db_table': 'treatments',
                'ordering': ['name_en'],
            },
        ),
        migrations.AddField(
            model_name='practitionertreatment',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_treatments', to='treatments.treatment'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['category', 'is_active'], name='treatments_categor_3d8315_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['clinic', 'is_active', 'deleted_at'], name='treatments_clinic__b93e99_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['clinic', 'status'], name='treatments_clinic__3435dc_idx'),
        ),
        migrations.AddIndex(
            model_name='practitionertreatment',
            index=models.Index(fields=['practitioner', 'treatment'], name='practitione_practit_a71a59_idx'),
        ),
        migrations.AddConstraint(
            model_name='practitionertreatment',
            constraint=models.UniqueConstraint(fields=('practitioner', 'treatment'), name='unique_practitioner_treatment'),
        ),
    ]
