# Generated by Django 5.2.4 on 2026-09-06 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_clinicbranch_alter_clinic_options_clinic_address_ar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('app_open', 'App Open'), ('clinic_view', 'Clinic View'), ('whatsapp_tap', 'WhatsApp Tap'), ('call_tap', 'Call Tap'), ('maps_tap', 'Maps Tap'), ('lead_submitted', 'Lead Submitted')], max_length=50)),
                ('anonymous_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='clinics.clinic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['clinic', 'event_type', 'timestamp'], name='analytics_e_clinic__88b45c_idx'), models.Index(fields=['timestamp'], name='analytics_e_timesta_47536d_idx')],
            },
        ),
    ]
