# Generated by Django 5.2.4 on 2026-09-06 14:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_lead_clinic', 'New Lead → Clinic'), ('lead_confirmation_patient', 'Lead Confirmation → Patient'), ('referral_milestone', 'Referral Milestone → Patient'), ('discount_collected', 'Discount Collected → Patient'), ('discount_redeemed', 'Discount Redeemed → Patient')], max_length=50)),
                ('channel', models.CharField(choices=[('push', 'Push Notification'), ('sms', 'SMS'), ('email', 'Email')], default='push', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='notificatio_recipie_218e2a_idx'), models.Index(fields=['status', 'created_at'], name='notificatio_status_dee16f_idx')],
            },
        ),
    ]
