# Generated by Django 5.2.4 on 2026-09-06 12:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('suspend_clinic', 'Suspend Clinic'), ('update_subscription', 'Update Subscription'), ('moderate_content', 'Moderate Content'), ('redeem_discount', 'Redeem Discount'), ('update_settings', 'Update Settings')], max_length=50)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type', 'created_at'], name='admin_audit_action__226336_idx')],
            },
        ),
    ]
