# Generated by Django 5.2.4 on 2026-09-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action_type',
            field=models.CharField(choices=[('suspend_clinic', 'Suspend Clinic'), ('activate_clinic', 'Activate Clinic'), ('verify_clinic', 'Verify Clinic'), ('update_subscription', 'Update Subscription'), ('moderate_content', 'Moderate Content'), ('redeem_discount', 'Redeem Discount'), ('update_settings', 'Update Settings')], max_length=50),
        ),
    ]
